export interface LoadDataOptions {
  /** 要加载的数据，为2024-2形式 */
  range: string;
}

export interface CompareLastMonth {
  compareLastMonth: number;
  compareLastMonthPercent: number;
}

export interface CompareLastYear {
  compareLastYear: number;
  compareLastYearPercent: number;
}

export interface NewLineItem {
  ch: string;
  cityCh: string;
  cityEn: string;
}

export interface NewLines {
  count: number;
  operationLength: number;
  detail?: NewLineItem[];
}

// Generated by https://quicktype.io
export interface DashboardData {
  id?: string;
  year: string;
  month: string;
  days: number;
  cityCount: number;
  lines: number;
  operationLength: number;
  runs: number;
  passengerCapacity: PassengerCapacity;
  inStationCapacity: number;
  passengerStrong: PassengerStrong;
  newLines: NewLines;
  largeVolume: VolumeSummary;
  mediumVolume: VolumeSummary;
  smallVolume: VolumeSummary;
  cities: City[];
  originLink?: string;
  summaries: string[];
}

export interface City {
  number: number;
  city: string;
  lines: number;
  operationLength: number;
  passengerCapacity: number;
  inStationCapacity: number;
  passengerStrong: number;
}

export interface VolumeSummary {
  lines: number;
  operationLength: number;
  passengerCapacity: number;
  inStationCapacity: number;
}

export interface PassengerCapacity extends CompareLastMonth, CompareLastYear {
  value: number;
}

export interface PassengerStrong {
  value: number;
  compareLastMonthPercent: number;
  compareLastYearPercent: number;
}
