name: Auto Merge Release/* PR

on:
  pull_request:
    branches:
      - release/*
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git fetch origin
          gh pr merge ${{ github.event.pull_request.html_url }} --rebase

      - name: Get Tag
        id: get_tag
        run: |
          echo "version=$(echo '${{ github.head_ref }}' | sed 's/refs\/heads\/release\///')" >> $GITHUB_OUTPUT

      - name: Push Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          custom_tag: ${{ steps.get_tag.outputs.version }}
          tag_prefix: ""
