name: Auto Merge Release/* PR

on:
  pull_request:
    branches:
      - release/*
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Source Commit SHA
        id: get_sha
        run: |
          echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git fetch origin
          gh pr merge ${{ github.event.pull_request.html_url }} --merge --delete-branch
